config/routes.rb
Rails.application.routes.draw do
  resources :courses
  get 'pages/about'

  get 'pages/location'

  # Вывод корневой страницы
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

	def star_number()
		self.star.blank? ? 1 : self.star
	end

	def cover()
		self.image.blank? ? "default.png" : self.image 
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:image, :video, :title, :star, :description, :public)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def location
  end

  def home
    #@courses = Course.all
    @courses = Course.where(public: true)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :image, id: :course_image, placeholder: "Изображение", class: "form-control" %>
  </div>

<!--
  <div class="field">
     <%= form.label :video %> Добавим из bootstap-->    
  <div class="form-group">
    <%= form.text_field :video, id: :course_video, placeholder: "Видео", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_field :title, id: :course_title, placeholder: "Название", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.number_field :star, value: course.star_number, min: "1", max: "5", id: :course_star, placeholder: "Рейтинг", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.text_area :description, id: :course_description, placeholder: "Описание", length: "800", class: "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :public, id: :public, class: "form-check-input" %>
    <label for="public" class="form-check-label">Опубликовать?</label>
  </div>
  <br>
<!--   <div class="actions">
    <%= form.submit %>
  </div> --> 
  <button type = "submit" class="btn-primary">Сохранить</button>
  <%= link_to "Открыть все курсы", courses_path, class: "btn btn-secondary" %> 
<% end %>

app/views/courses/edit.html.erb
<h1>Редактировать курс</h1>

<%= render 'form', course: @course %>

<!-- <%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %> -->

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Курсы</h1>

<%= link_to 'Добавить курс ', new_course_path, class: "btn btn-primary" %>

<table class = "table table-borderless">
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= link_to course.title, course %></td>
        <td><%= link_to edit_course_path(course) do%>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do%>
              <i class="fa-regular fa-trash-can"></i>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1>Новый курс</h1>

<%= render 'form', course: @course %>

<!-- <%= link_to 'Back', courses_path %> -->

app/views/courses/show.html.erb
    <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
    <div id="player"></div>

    <script>
      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);


      // // 4. The API will call this function when the video player is ready.
      // function onPlayerReady(event) {
      //   event.target.playVideo();
      // }

      // // 5. The API calls this function when the player's state changes.
      // //    The function indicates that when playing a video (state=1),
      // //    the player should play for six seconds and then stop.
      // var done = false;
      // function onPlayerStateChange(event) {
      //   if (event.data == YT.PlayerState.PLAYING && !done) {
      //     setTimeout(stopVideo, 6000);
      //     done = true;
      //   }
      // }

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '360',
          width: '100%',
          videoId: '<%= @course.video %>',
          // events: {
          //   'onReady': onPlayerReady,
          //   'onStateChange': onPlayerStateChange
          // }
        });
      }

      function stopVideo() {
        player.stopVideo();
      }
    </script>


 <div class="card mb-3" > <!--Убрали ограничение по ширине style="max-width: 540px;"> -->
  <div class="row g-0">
    <div class="col-md-4">
      <!-- <img src="..." class="img-fluid rounded-start" alt="..."> -->
        <%= image_tag @course.cover, class: "img-fluid rounded-start", alt: "Алексей Лобзов" %>      
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @course.title %></h5>
        <p class="card-text"><%= @course.description %></p>
        <% (1..5).each do |v| %>
          <% if v > @course.star %>
            <i class="fa-regular fa-star"></i>
          <% else %>
            <i class="fa-solid fa-star"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @course.image %>
</p>

<p>
  <strong>Video:</strong>
  <%= @course.video %>
</p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Star:</strong>
  <%= @course.star %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleUdemy</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  <script src="https://kit.fontawesome.com/eed40e0fd7.js" crossorigin="anonymous"></script>

  <script src="https://vk.com/js/api/openapi.js?169" type="text/javascript"></script>  
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="<%= root_path %>">Lodemo</a>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= courses_path %>">Видео</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pages_about_path%>">О прооекте</a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="#">Контакты</a> -->
            <%= link_to "Контакты", pages_location_path, class: "nav-link"  %>
          </li>
        </ul>
      </div>
    </div>
    
  </nav>
  <script type="text/javascript">
        VK.init({
          apiId: 51578774,
          onlyWidgets: true
        });
  </script>  
  <div class="container pt-4 border" > 
    <div class="row">
      <div class = "col-md-10 offset-md-1">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>
  

app/views/pages/about.html.erb
<h2> О проекте</h2>

<div class="card shadow p-3 mb-5 bg-white rounded">
	<div class = "card-body">
		<div class="row">
			<div class = "col-md-6">
				<div id="musubiufa">
				<script type="text/javascript">
				    VK.Widgets.Group("musubiufa", {mode: , width: "300", height: "400"}, 12615153);
				</script>
				</div>
			</div>
			<div class = "col-md-6">
				<div class="card-body shadow-sm p-3 mb-5 bg-white rounded">
					<div class="row">
						<div class="col-md-3">
							<%= image_tag "Lobzov.jpg", class: "rounded-circle img-fluid", alt: "Алексей Лобзов"%>
						</div>
						<div class="col-md-9">
							<span>
								<h4>Алексей Лобзов</h4>
								Руководитель клуба Aikido Musubi, г.Уфа
							</span>
						</div>
					</div>
				</div>
			</div>			
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<br>

<div class="row">
	<% @courses.each do |course| %>
		<div class="col-md-3">
			<div class="card">

				<%= link_to course do %>
					<%= image_tag course.cover, class: "card-img-top" %>
				<% end %>
				<div class="card-body">
					<h5 class="card-title">course.title</h5>
		      <% (1..5).each do |v| %>
		        <% if v > course.star %>
		          <i class="fa-regular fa-star"></i>
		        <% else %>
		          <i class="fa-solid fa-star"></i>
		        <% end %>
		      <% end %>
					<!-- <p class="card-text"> <%= course.description %> </p> -->
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/pages/location.html.erb
<h2>Контакты</h2>
<div class="card shadow p-3 mb-5 bg-white rounded">
	<div class="card-body">
		<div class="row">
			<p>Вы можете найти нас здесь:</p>
			<iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A3f777a20e60b569a8e47be34b053948243ae97f5b744e270c032239d2507d458&amp;source=constructor" width="500" height="400" frameborder="0"></iframe>
		</div>
	</div>
</div>